# src/OC/CoreBundle/Resources/config/routing.yml

oc_core_home:
    path: /core
    defaults:
        _controller: OCCoreBundle:Core:index

oc_core_contact:
    path: /contact
    defaults:
        _controller: OCCoreBundle:Core:contact
